### ISSUE TITLE
Get a public link for the SSI repo slack channel

### ISSUE THREAD

**Issue by gixita** [energywebfoundation/ssi#15]
We should have a public link for the slack channel or we should remove completely the possibility to contact us that way. As most of the slack channels are private, we may need to check with EWF how to specify that the channel is publicly available.

**Comment by jrhender** [comment]
I suggest that we "remove completely the possibility to contact us that way". Many people using this repo won't be EWF members and so won't have access to the EWF Members slack

**Comment by jrhender** [comment]
Closing this issue given the above as Slack is not in the listed contact options: https://github.com/energywebfoundation/ssi#questions-and-support
